version: '3.9'
services:
  api:
    build: .
    container_name: senasa-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn","senasa_pipeline.presentation.api:app","--host","0.0.0.0","--port","8000"]
